### ISSUE TITLE
Remove Quotations in Term Definitions?

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/fido#142]
Currently there are several definitions that have quotation marks in them. I believe this signals that the definitions are direct citations from literature, but I'm not entirely sure.

How do we feel about removing the quotation marks? Likely these definitions will need to change to reflect true Aristotelian form in the future, so my thought is we should remove them and rely on the annotation properties to structure this 'metadata.'

Example: 
comparator:
"A performer to which a performance report is not deliver, and to which a recipient can be compared" http://purl.obolibrary.org/obo/fio#FIO_0000037

**Comment by CooperStansbury** [comment]
@grosscol @zachll it turns out the quotation marks are not part of the .owl file. They are not present in the raw file nor are they present in protege. 

I believe that they are a product of the ROBOT query used to extract them from the ontology, but I cannot figure out where/when they're generated. They appear in [the dictionary](https://github.com/Display-Lab/fio/blob/master/DICTIONARY.md) and in the `dictionary.csv` file in the `.gitignore` but nowhere else. 

I do not think it's worth it to chase this down, but maybe @grosscol will know what's going on quickly. Close when ready.

**Comment by grosscol** [comment]
Related to and can be rolled into #141
