### ISSUE TITLE
change FIDO's name to the performance summary display ontology (PSDO)

### ISSUE THREAD

**Issue by zachll** [Display-Lab/fido#150]
What we currently are calling FIDO is about performance summary displays that could be used in contexts other than feedback interventions, therefore we should consider renaming the ontology.

**Comment by CooperStansbury** [comment]
@zachll does this need more discussion or can I rename in a working branch?

**Comment by zachll** [comment]
No more discussion needed, please proceed with renaming

**Comment by CooperStansbury** [comment]
#151
